name: countries
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  freezed_annotation: ^1.0.0
  flutter_redux: ^0.8.2
  http: ^0.13.4
  meta: ^1.7.0
  redux: ^5.0.0
  json_annotation: ^4.4.0
  redux_epics: ^0.15.0
  string_validator: ^0.3.0
  flutter_svg: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  build_runner: ^2.1.5
  freezed: ^1.0.2+1
  json_serializable: ^6.1.1

dependency_overrides:
  rxdart: ^0.27.3

flutter:
  generate: true
  uses-material-design: true